name: Build Cogni Reports Lamnda

on:
  pull_request:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Build Nix package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: DeterminateSystems/determinate-nix-action@v3.6.1
      - run: nix build .
